"""R38 material-builder BLUEPRINT; all asset paths are behind an unbound gate.

No __main__, Unreal import, source-image modification, or runnable native owner.
The exact frozen 70/73 graph snapshots remain unchanged; missing sampler-source
fields are checked separately, including all original texture samples.
"""
import importlib.util
from pathlib import Path

OWNER = 'scripts/unreal/exterior-context-yard-soft-coherence-materials-r38-draft.py'
SCHEMA = 'brezi-r38-soft-ground-two-material-one-mask-builder-draft'
_spec = importlib.util.spec_from_file_location('r38_draft_guards_for_materials',
    Path(__file__).with_name('exterior-context-yard-soft-coherence-guards-r38-draft.py'))
g = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(g)
FIELDS = ('srgb', 'compression_none', 'compression_settings', 'mip_gen_settings', 'filter',
    'address_x', 'address_y', 'power_of_two_mode', 'resize_during_build_x', 'resize_during_build_y',
    'lod_bias', 'max_texture_size', 'never_stream', 'virtual_texture_streaming',
    'flip_green_channel', 'do_scale_mips_for_alpha_coverage', 'adjust_brightness',
    'adjust_brightness_curve', 'adjust_vibrance', 'adjust_saturation', 'adjust_rgb_curve',
    'adjust_hue', 'adjust_min_alpha', 'adjust_max_alpha', 'chroma_key_texture')


def exact_enum(enum, spelling):
    """Exact enum token, allowing only underscores generated by Python reflection."""
    token = spelling.replace('_', '').upper()
    matches = [k for k in dir(enum) if k.replace('_', '').upper() == token]
    g.require(len(matches) == 1, 'Required installed reflected enum unavailable: '+spelling)
    return getattr(enum, matches[0])


def preflight_enums(u):
    return {'filter': exact_enum(u.TextureFilter, 'TF_BILINEAR'),
        'sampler': exact_enum(u.SamplerSourceMode, 'SSM_FROM_TEXTURE_ASSET'),
        'mips': exact_enum(u.TextureMipGenSettings, 'TMGS_NO_MIPMAPS'),
        'address': exact_enum(u.TextureAddress, 'TA_CLAMP'),
        'compression': exact_enum(u.TextureCompressionSettings, 'TC_MASKS'),
        'encoding': exact_enum(u.TextureSourceEncoding, 'TSE_NONE'),
        'powerOfTwo': exact_enum(u.TexturePowerOfTwoSetting, 'NONE'),
        'masked': exact_enum(u.BlendMode, 'BLEND_MASKED'),
        'float1': exact_enum(u.CustomMaterialOutputType, 'CMOT_FLOAT1'),
        'float2': exact_enum(u.CustomMaterialOutputType, 'CMOT_FLOAT2'),
        'float3': exact_enum(u.CustomMaterialOutputType, 'CMOT_FLOAT3'),
        'masks': exact_enum(u.MaterialSamplerType, 'SAMPLERTYPE_MASKS'),
        'maskMipMode': exact_enum(u.TextureMipValueMode, 'TMVM_NONE')}


def preflight_reflection(u):
    """Read CDO fields before any import; never alter the class default object."""
    texture = u.get_default_object(u.Texture2D)
    for key in FIELDS:
        texture.get_editor_property(key)
    color = texture.get_editor_property('source_color_settings')
    color.get_editor_property('encoding_override')
    down = texture.get_editor_property('downscale')
    down.get_editor_property('default');down.get_editor_property('per_platform')
    texture.get_editor_property('alpha_coverage_thresholds')
    sample = u.get_default_object(u.MaterialExpressionTextureSample)
    for key in ('sampler_source', 'sampler_type', 'mip_value_mode', 'automatic_view_mip_bias'):
        sample.get_editor_property(key)
    for name in ('MaterialExpressionConstant', 'MaterialExpressionConstant3Vector', 'MaterialExpressionCustom',
        'MaterialExpressionTextureCoordinate', 'MaterialExpressionComponentMask', 'MaterialExpressionMaterialFunctionCall', 'CustomInput'):
        getattr(u, name)
    for name in ('get_material_expressions', 'create_material_expression', 'connect_material_expressions',
        'connect_material_property', 'recompile_material', 'get_material_expression_input_names'):
        g.require(hasattr(u.MaterialEditingLibrary, name), 'Required reflected material API unavailable')
    return {'requiredPropertiesReadableBeforeImport': True, 'setterAvailabilityActuallyMeasured': False}


def scalar(value):
    return value if isinstance(value, (bool, int, float, str)) else str(value)


def texture_snapshot(u, texture):
    row = {'asset': texture.get_path_name(), 'values': {k: scalar(texture.get_editor_property(k)) for k in FIELDS},
        'size': [texture.blueprint_get_size_x(), texture.blueprint_get_size_y()],
        'sourceEncoding': str(texture.get_editor_property('source_color_settings').get_editor_property('encoding_override'))}
    down = texture.get_editor_property('downscale')
    row['downscale'] = {'default': float(down.get_editor_property('default')),
        'perPlatform': {str(k): float(v) for k, v in dict(down.get_editor_property('per_platform')).items()}}
    row['alphaCoverageThresholds'] = [float(getattr(texture.get_editor_property('alpha_coverage_thresholds'), k)) for k in 'xyzw']
    row['metadata'] = {k: u.EditorAssetLibrary.get_metadata_tag(texture, k) for k in
        ('BreziGeneratedBy', 'BreziSourceSha256', 'BreziTechnicalDataRole', 'BreziSourcePlanSha256')}
    return row


def expected_texture_values(enums):
    return {'srgb': False, 'compression_none': True, 'compression_settings': str(enums['compression']),
        'mip_gen_settings': str(enums['mips']), 'filter': str(enums['filter']),
        'address_x': str(enums['address']), 'address_y': str(enums['address']),
        'power_of_two_mode': str(enums['powerOfTwo']), 'resize_during_build_x': 0, 'resize_during_build_y': 0,
        'lod_bias': 0, 'max_texture_size': 0, 'never_stream': True, 'virtual_texture_streaming': False,
        'flip_green_channel': False, 'do_scale_mips_for_alpha_coverage': False,
        'adjust_brightness': 1., 'adjust_brightness_curve': 1., 'adjust_vibrance': 0.,
        'adjust_saturation': 1., 'adjust_rgb_curve': 1., 'adjust_hue': 0.,
        'adjust_min_alpha': 0., 'adjust_max_alpha': 1., 'chroma_key_texture': False}


def validate_mask_snapshot(row, enums):
    g.require(row['asset'] == g.MASK_ASSET and row['values'] == expected_texture_values(enums)
        and row['size'] == [2048, 2048] and row['sourceEncoding'] == str(enums['encoding'])
        and row['downscale'] == {'default': 1., 'perPlatform': {}}
        and row['alphaCoverageThresholds'] == [0., 0., 0., 0.],
        'Mask resizing/filtering/compression/encoding/adjustment policy differs')


def aux_snapshot(u, material):
    """Fields absent from the historical generic graph snapshot, not rewritten."""
    samplers, world = {}, {}
    for node in u.MaterialEditingLibrary.get_material_expressions(material):
        role = str(node.get_editor_property('desc'));cls = node.get_class().get_name()
        if cls == 'MaterialExpressionTextureSample':
            samplers[role] = str(node.get_editor_property('sampler_source'))
        if cls == 'MaterialExpressionWorldPosition':
            world[role] = str(node.get_editor_property('world_position_shader_offset'))
    return {'samplerSources': samplers, 'worldPositionShaderOffsets': world}


def _import_mask_blueprint(u, bundle, enums):
    assets = u.EditorAssetLibrary
    package = g.MASK_ASSET.split('.')[0]
    g.require(not assets.does_asset_exist(package), 'Fresh own generated-mask package required')
    task = u.AssetImportTask()
    for key, value in {'filename': bundle['plan']['permissionField']['path'],
        'destination_path': g.PREFIX+'/Textures', 'destination_name': 'T_soft_permission_r38',
        'automated': True, 'replace_existing': False, 'save': False}.items():
        task.set_editor_property(key, value)
    u.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])
    texture = assets.load_asset(package)
    g.require(isinstance(texture, u.Texture2D) and texture.get_path_name() == g.MASK_ASSET, 'Owned Texture2D import required')
    # Reflection must expose every field BEFORE configuration; no silent fallbacks.
    for key in FIELDS:
        texture.get_editor_property(key)
    values = expected_texture_values(enums)
    overrides = {'compression_settings': enums['compression'], 'mip_gen_settings': enums['mips'],
        'filter': enums['filter'], 'address_x': enums['address'], 'address_y': enums['address'],
        'power_of_two_mode': enums['powerOfTwo']}
    for key, value in values.items():
        texture.set_editor_property(key, overrides.get(key, value))
    down = texture.get_editor_property('downscale')
    down.set_editor_property('default', 1.)
    down.set_editor_property('per_platform', {})
    texture.set_editor_property('downscale', down)
    texture.set_editor_property('alpha_coverage_thresholds', u.Vector4(0., 0., 0., 0.))
    color = texture.get_editor_property('source_color_settings')
    color.set_editor_property('encoding_override', enums['encoding'])
    texture.set_editor_property('source_color_settings', color)
    for key, value in {'BreziGeneratedBy': OWNER, 'BreziSourceSha256': g.PNG_SHA,
        'BreziTechnicalDataRole': 'artist-generated-fixed-world-permission-field', 'BreziSourcePlanSha256': g.SOURCE_SHA}.items():
        assets.set_metadata_tag(texture, key, value)
    snapshot = texture_snapshot(u, texture)
    validate_mask_snapshot(snapshot, enums)
    g.require(assets.save_loaded_asset(texture, False), 'Cannot save owned mask')
    return texture, snapshot


def _add_nodes_blueprint(u, material, graph, mask_texture, enums):
    lib = u.MaterialEditingLibrary
    nodes = {str(n.get_editor_property('desc')): n for n in lib.get_material_expressions(material)}
    g.require(len(nodes) == 58, 'Exact initial backdrop copy required')
    pending = [n for n in graph['nodes'] if n['role'] not in nodes]
    for row in pending:
        cls = getattr(u, row['class'])
        node = lib.create_material_expression(material, cls, -700, 900)
        g.require(node is not None, 'Cannot create declared response node')
        node.set_editor_property('desc', row['role']);values = row['values']
        if row['class'] == 'MaterialExpressionCustom':
            ports = []
            for name, _, _ in row['inputs']:
                port = u.CustomInput();port.set_editor_property('input_name', name);ports.append(port)
            node.set_editor_property('inputs', ports)
            node.set_editor_property('code', values['code'])
            node.set_editor_property('output_type', enums['float'+str(1+int(values['output_type'].split(': ')[1].split('>')[0]))])
        elif row['class'] == 'MaterialExpressionMaterialFunctionCall':
            function = u.EditorAssetLibrary.load_asset(values['material_function'])
            g.require(function is not None and node.set_material_function(function), 'Installed inherited dither function required')
        else:
            for key, value in values.items():
                if key == 'constant': value = u.LinearColor(*value)
                if key == 'texture': value = mask_texture
                if key == 'sampler_type': value = enums['masks']
                if key == 'mip_value_mode': value = enums['maskMipMode']
                node.set_editor_property(key, value)
        if row['role'] == g.TAG+'fixed-world-yard-mask':
            node.set_editor_property('sampler_source', enums['sampler'])
        nodes[row['role']] = node
    for row in pending:
        for pin, source, output in row['inputs']:
            if source is not None:
                g.require(lib.connect_material_expressions(nodes[source], output, nodes[row['role']], '' if pin == 'None' else pin), 'Declared node connection failed')
    for root in ('BASE_COLOR', 'NORMAL', 'ROUGHNESS', 'OPACITY_MASK'):
        row = graph['roots'][root]
        if row is not None:
            g.require(lib.connect_material_property(nodes[row[0]], row[1], getattr(u.MaterialProperty, 'MP_'+root)), 'Declared response root failed')


def build_materials(u, bundle, binding, graph_snapshot, shared_texture_snapshot):
    g.require_native_binding(binding)  # always fails in this unbound draft, before ANY UObject calls.
    enums = preflight_enums(u)
    reflection = preflight_reflection(u)
    g.validate_policy(bundle['samplingPolicy'])
    adaptation = g.validate_native_graphs(bundle['graphs'], bundle['nativeGraphs'])
    old = u.EditorAssetLibrary.load_asset(bundle['originalBackdropAsset'])
    substrate = u.EditorAssetLibrary.load_asset(bundle['originalSubstrateAsset'])
    g.require(isinstance(old, u.Material) and isinstance(substrate, u.Material), 'Two actual old source materials required')
    g.require(graph_snapshot(u, old) == bundle['originalGraph'], 'Actual original58 graph differs')
    old_aux = aux_snapshot(u, old)
    originals = {old.get_path_name(): graph_snapshot(u, old), substrate.get_path_name(): graph_snapshot(u, substrate)}
    original_aux = {m.get_path_name(): aux_snapshot(u, m) for m in (old, substrate)}
    shared_before = shared_texture_snapshot(u)
    g.require(all(not u.EditorAssetLibrary.does_asset_exist(p.split('.')[0]) for p in g.ASSETS.values()), 'Fresh two-material namespace required')
    texture, texture_report = _import_mask_blueprint(u, bundle, enums)
    materials, reports = {}, {}
    for key, asset in g.ASSETS.items():
        m = u.EditorAssetLibrary.duplicate_asset(old.get_path_name(), asset.split('.')[0])
        g.require(isinstance(m, u.Material) and graph_snapshot(u, m) == bundle['originalGraph'], 'Initial exact58 graph copy differs')
        _add_nodes_blueprint(u, m, bundle['nativeGraphs'][key], texture, enums)
        if key == 'substrate':
            m.set_editor_property('blend_mode', enums['masked']);m.set_editor_property('opacity_mask_clip_value', .5)
        errors = list(u.MaterialEditingLibrary.recompile_material(m))
        g.require(errors == [] and graph_snapshot(u, m) == bundle['nativeGraphs'][key], 'Actual proposed70/73 native-adapted graph/compile differs')
        expected_aux = {'samplerSources': {**old_aux['samplerSources'], g.TAG+'fixed-world-yard-mask': str(enums['sampler'])},
            'worldPositionShaderOffsets': old_aux['worldPositionShaderOffsets']}
        g.require(aux_snapshot(u, m) == expected_aux, 'Original sampler source/world-position policy changed')
        metadata = {'BreziGeneratedBy': OWNER, 'BreziSourcePlanSha256': g.SOURCE_SHA, 'BreziSourceOriginalMaterial': old.get_path_name(), 'BreziR38Role': key}
        for name, value in metadata.items(): u.EditorAssetLibrary.set_metadata_tag(m, name, value)
        g.require(u.EditorAssetLibrary.save_loaded_asset(m, False), 'Cannot save new isolated material')
        materials[key] = m
        reports[key] = {'asset': asset, 'graph': graph_snapshot(u, m), 'graphSha256': g.digest(bundle['nativeGraphs'][key]),
            'aux': expected_aux, 'compileErrors': errors, 'metadata': metadata}
    g.require(shared_texture_snapshot(u) == shared_before and all(graph_snapshot(u, u.EditorAssetLibrary.load_asset(p)) == row
        and aux_snapshot(u, u.EditorAssetLibrary.load_asset(p)) == original_aux[p] for p, row in originals.items()), 'Original graphs/shared texture settings changed')
    report = {'schema': SCHEMA, 'owner': OWNER, 'sourceStudy': bundle['source'], 'materials': reports,
        'maskTexture': texture_report, 'samplingPolicy': bundle['samplingPolicy'], 'nativeGraphAdaptation': adaptation,
        'reflectionPreflight': reflection, 'sharedTextureWitness': shared_before,
        'originalGraphWitness': originals, 'originalAuxWitness': original_aux,
        'newPackageAssets': sorted([*g.ASSETS.values(), g.MASK_ASSET]),
        'sourcePhotoPixelsEdited': False, 'nativeTexelsDecoded': False, 'nativeGpuPixelFormatVerified': False,
        'nativeGpuOutsideEquivalenceVerified': False, 'materialPackagesIndependentlyUnloaded': False,
        'nativeAppearanceAccepted': False, 'fullPhotorealismAccepted': False, 'performanceAccepted': False}
    return materials, report


def verify_materials(u, bundle, binding, report, graph_snapshot, shared_texture_snapshot):
    g.require_native_binding(binding)
    enums = preflight_enums(u)
    g.require(report['schema'] == SCHEMA and report['owner'] == OWNER and report['sourceStudy'] == bundle['source']
        and report['newPackageAssets'] == sorted([*g.ASSETS.values(), g.MASK_ASSET]), 'Closed own material report required')
    g.validate_policy(report['samplingPolicy'])
    texture = u.EditorAssetLibrary.load_asset(g.MASK_ASSET)
    current = texture_snapshot(u, texture);validate_mask_snapshot(current, enums)
    g.require(current == report['maskTexture'], 'Saved mask settings changed')
    materials = {}
    for key, asset in g.ASSETS.items():
        m = u.EditorAssetLibrary.load_asset(asset);row = report['materials'][key]
        g.require(graph_snapshot(u, m) == bundle['nativeGraphs'][key] == row['graph'] and
            aux_snapshot(u, m) == row['aux'], 'Saved graph/sampler/world-position route changed')
        for name, value in row['metadata'].items():
            g.require(u.EditorAssetLibrary.get_metadata_tag(m, name) == value, 'Owned material provenance changed')
        materials[key] = m
    g.require(shared_texture_snapshot(u) == report['sharedTextureWitness'] and all(
        graph_snapshot(u, u.EditorAssetLibrary.load_asset(p)) == row and
        aux_snapshot(u, u.EditorAssetLibrary.load_asset(p)) == report['originalAuxWitness'][p]
        for p, row in report['originalGraphWitness'].items()), 'Original graphs/shared texture policy changed')
    return materials
