// Changed R43 saved-reader contracts only; actual immutable records, no UE.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {ACTUAL,validateBoundaryHeader,validatePlanClosure,validateBoundaryContent,validateRootAudit,validateSpawnObservations} from './exterior-editor-source-r31.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url)).replace(/\/$/,'');
const source=path.join(root,'output/unreal/exterior-20261002-r43b');
const read=async p=>JSON.parse(await fs.readFile(p,'utf8'));
const r=await read(path.join(source,'boundary-native-report-r2.json')),plan=await read(r.selectedPlan.path),pf=await read(r.sourcePreflight.path),base=await read(r.baseNativeReport.path),audit=await read(path.join(source,'root-native-success-byte-audit-r43b-r2.json'));
test('exact successful R43b R2 dispatch rejects failed source and promotion',()=>{validateBoundaryHeader(r,{root,source});const changed=structuredClone(r);changed.nativeApplied=false;assert.throws(()=>validateBoundaryHeader(changed,{root,source}));changed.nativeApplied=true;changed.activeOutputPromoted=true;assert.throws(()=>validateBoundaryHeader(changed,{root,source}));assert.throws(()=>validateBoundaryHeader(r,{root,source:path.join(root,'output/unreal/exterior-20261002-r43a')}));});
test('real1331 plan self-pin closes real1332 report/PF, corruption rejects',()=>{assert.equal(Object.keys(plan.inputFiles).length,1331);assert.equal(Object.keys(pf.inputFiles).length,1332);validatePlanClosure(plan,pf,r);const changed=structuredClone(plan);changed.inputFiles[r.selectedPlan.path]='f'.repeat(64);assert.throws(()=>validatePlanClosure(changed,pf,r));const other=structuredClone(pf);delete other.inputFiles[r.selectedPlan.path];assert.throws(()=>validatePlanClosure(plan,other,r));});
test('actual15package map-only scope rejects extra artifact and old non-map mutation',async()=>{const before=await read(base.afterContentInventory.path),after=await read(r.afterContentInventory.path);validateBoundaryContent(before,after,r.newPackages,r.assetDelta);const changed=structuredClone(after);changed['Brezi/foreign.uasset']={sha256:'a'.repeat(64),bytes:1};assert.throws(()=>validateBoundaryContent(before,changed,r.newPackages,r.assetDelta));delete changed['Brezi/foreign.uasset'];const key=Object.keys(before).find(k=>k!=='Brezi/Maps/Brezi.umap');changed[key]={sha256:'b'.repeat(64),bytes:1};assert.throws(()=>validateBoundaryContent(before,changed,r.newPackages,r.assetDelta));});
test('actual native class/default zero bits and CPU audit tier remain exact',async()=>{const observations=await read(r.newActorSpawnObservations.path),before={'/Game/Brezi/Maps/Brezi.Brezi:PersistentLevel.StaticMeshActor_197':plan.newActorTemplate};validateSpawnObservations(observations,r,before);const changed=structuredClone(observations);changed.actualObservations[0].actorTransform[1][1]=-0.;assert.throws(()=>validateSpawnObservations(changed,r,before));const pins={reportPin:audit.nativeReport,processPin:audit.nativeProcess,rawPin:audit.rawNativeProcess};validateRootAudit(audit,r,pins);const other=structuredClone(audit);other.newNativeActorOrAttributeDecodeByAudit=true;assert.throws(()=>validateRootAudit(other,r,pins));other.newNativeActorOrAttributeDecodeByAudit=false;other.all1343FrozenSourcePinsExact=false;assert.throws(()=>validateRootAudit(other,r,pins));assert.equal(ACTUAL.nativePid,44798);});
