#pragma once
// Generated by Tools/water_binding.py; diagnostic saved-water binding only.
static constexpr const TCHAR* BreziCausticsWaterBindingSha256 = TEXT("05186c2144e8415f6f6d68043f50d996320130bc717b2ef1b7f0088987a7049d");
static constexpr const TCHAR* BreziCausticsWaterBindingSha1 = TEXT("c93ff89696a09791994ba157a2d130269655db1d");
static constexpr const TCHAR* BreziCausticsWaterMaterialSha1 = TEXT("4c92d95d6378fbdd6bfaef7625ecd7f18d82863f");
static constexpr const TCHAR* BreziCausticsWaterMaterialRelativePath = TEXT("Content/Brezi/OpticsGenerated/M_PoolWater.uasset");
