import Link from '@/app/project-link';
import { ArrowUpRight, BookOpen, Box, FileText, MapPinned, PanelsTopLeft, Archive, ArrowRight } from 'lucide-react';
import { ProjectNav } from './project-nav';
import { SiteDrawing } from './site-drawing';
import { ACTIVE_DESIGN, designHref } from '@/lib/twin-design-selection';
import { PLAN_ROOMS, numberSk } from '@/lib/plan-documentation';
import { SOURCES, type SourceRecord } from '@/lib/twin-site';
import './globals.css';
import './project.css';

const plan=designHref('/podorys',ACTIVE_DESIGN),three=designHref('/3d',ACTIVE_DESIGN);
export function ProjectHome({docs=false}:{docs?:boolean}) {
  const sources:SourceRecord[]=Object.values(SOURCES).filter(s=>['PROJECT_DESIGN','CURRENT_REGISTER','UNRESOLVED_AS_BUILT'].includes(s.kind));
  return <div className="project-app"><ProjectNav active={docs?'docs':'overview'}/><main className="project-content" id="project-content">
    <div className="project-heading"><div><p className="project-eyebrow">BŘEZÍ U MIKULOVA <span>/</span> RODINNÝ DOM</p><h1>{docs?'Dokumentácia domu.':'Dom v Březí.'}</h1><p>{docs?'Výkresy, rozmery a podklady k hlavnému návrhu.':'Pôdorys, priestor a dokumentácia na jednom mieste.'}</p></div><div className="project-approved"><span>HLAVNÝ NÁVRH</span><strong>C <i>/</i> B <i>/</i> B</strong><small>Dispozícia · technická · obývačka</small></div></div>
    <div className="project-grid"><section className="project-plan-card"><div className="project-card-heading"><div><span className="project-eyebrow">01 / DOM A POZEMOK</span><h2>Pôdorys a osadenie</h2></div><Link href={plan} aria-label="Otvoriť interaktívny pôdorys"><ArrowUpRight size={23}/></Link></div><Link href={plan} className="project-drawing-link" aria-label="Preskúmať pôdorys a parcelu"><SiteDrawing/></Link><div className="project-plan-caption"><span><i/>Hranica parcely z katastra</span><Link href={`${plan}&site=1`}>Osadenie domu<ArrowRight size={16}/></Link></div><p className="project-data-note">Uličný aj pravý odstup domu je 3,00 m. Situácia C3 s upraveným osadením podľa zadania stavebníka.</p></section>
    <aside className="project-launches"><Link className="project-launch primary" href={docs?designHref('/docs/manual',ACTIVE_DESIGN):plan}><span className="project-launch-icon">{docs?<BookOpen/>:<PanelsTopLeft/>}</span><div><small>{docs?'DOKUMENTÁCIA / 01':'POKRAČOVAŤ V NÁVRHU'}</small><h2>{docs?'Manuál domu':'Pôdorys interiéru'}</h2><p>{docs?'Miestnosť po miestnosti. Rozmery, vybavenie a výkresy pripravené na tlač.':'Všetky miestnosti, presné rozmery, vybavenie aj hranice pozemku.'}</p></div><span className="project-launch-action">{docs?'Otvoriť manuál':'Otvoriť pôdorys'}<ArrowUpRight size={18}/></span></Link>
    <Link className="project-launch secondary" href={three}><Box size={24}/><div><h2>Prejsť sa domom</h2><p>3D priestor hlavného návrhu C/B/B.</p></div><ArrowUpRight size={19}/></Link>
    <Link className="project-launch secondary" href={docs?'/docs/model':'/docs'}>{docs?<MapPinned size={24}/>:<BookOpen size={24}/>}<div><h2>{docs?'Technický model':'Dokumentácia'}</h2><p>{docs?'Parcela, základy, siete a zdroje.':'Manuál, výkresy a zdrojové podklady.'}</p></div><ArrowUpRight size={19}/></Link>
    <div className="project-stats"><div><strong>{PLAN_ROOMS.length}</strong><span>miestností</span></div><div><strong>{numberSk(PLAN_ROOMS.reduce((s,r)=>s+r.area,0),2)} <small>m²</small></strong><span>čistej plochy vrátane garáže</span></div></div></aside></div>
    {docs&&<section className="project-decision"><div className="project-decision-icon"><FileText size={23}/></div><div><p className="project-eyebrow">AK-03 / ODBORNÉ ZDÔVODNENIE</p><h2>Prečo má H200 práve túto skladbu.</h2><p>Princíp akustickej steny, reprodukovateľný výpočet, poradie dosiek a literatúra vrátane výskumu NRC.</p></div><Link href="/docs/akustika-h200">Čítať odbornú správu<ArrowRight size={17}/></Link></section>}
    {docs?<section className="project-documents" aria-labelledby="sources-title"><div className="project-section-heading"><div><p className="project-eyebrow">02 / ZDROJOVÉ PODKLADY</p><h2 id="sources-title">Z čoho vychádzame</h2></div><span>{sources.length} podkladov</span></div><div className="project-source-list">{sources.map(source=><details key={source.id}><summary><FileText size={20}/><span><strong>{source.title}</strong><small>{source.date}</small></span><b>{source.kind==='CURRENT_REGISTER'?'Kataster / register':source.kind==='UNRESOLVED_AS_BUILT'?'Chýbajúci podklad':'Projektový podklad'}</b><span className="source-expand">+</span></summary><div><p>{source.detail}</p>{source.href&&<a href={source.href} target="_blank" rel="noreferrer">Otvoriť zdroj<ArrowUpRight size={15}/></a>}<Link href="/docs/model">Zobraziť súvislosti v technickom modeli<ArrowRight size={15}/></Link></div></details>)}</div></section>:<section className="project-decision"><div className="project-decision-icon"><FileText size={23}/></div><div><p className="project-eyebrow">ROZHODNUTIE / 13. SEPTEMBER 2026</p><h2>Všetky ďalšie úpravy vychádzajú z C/B/B.</h2><p>Dispozícia C · Výklenok, technická miestnosť B a obývacia zóna B. Predchádzajúce návrhy zostávajú zachované v histórii.</p></div><Link href="/archiv"><Archive size={17}/>Archív návrhov<ArrowRight size={17}/></Link></section>}
    <footer className="project-footer"><span>DOM 6012/26 <i>·</i> Súkromný projekt domu</span><Link href="/archiv">História návrhov<ArrowUpRight size={14}/></Link></footer>
  </main></div>;
}
