// Synthetic receipt controls only; the native reader remains the proof producer.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {test} from 'node:test';
import {expectedPoolCopingInputs,validatePoolCopingReceipt,POOL_COPING_SHADER_HASHES} from './package-gate.mjs';
const expected=expectedPoolCopingInputs(),ref=expected.reference;
const digest=v=>createHash('sha256').update(v).digest('hex'),h='a'.repeat(64),clone=structuredClone;
const ids=Object.keys(ref.sourceRecords).sort(),base='/Game/Brezi/Geometry/brezi-twin/Materials/MAT_0102.MAT_0102';
function fixture(inactive=false){
 const recipe={reference:ref,recipeInputs:expected.recipeInputs},recipeCanonicalJson=JSON.stringify(recipe),recipeSha256=digest(recipeCanonicalJson),owned=`/Game/Brezi/PoolCoping/R_${recipeSha256.slice(0,16)}`,material=owned+'/Materials/M_PoolCoping.M_PoolCoping';
 const selectedBefore=Object.fromEntries(ids.map(id=>[id,{actor:id,component:'Mesh',mesh:`/Game/Brezi/Geometry/brezi-twin/StaticMeshes/${id}.${id}`,meshMaterial:base,state:'source',effectiveMaterial:base,overrides:[],nativeSnapshot:{fixture:true},sourceProof:{triangles:12,windingMultiplicityVerified:true,sourceToleranceMm:.002,uv0Tolerance:.000002,snapshotSha256:h,maximumPositionErrorMm:0,maximumUv0Error:0}}]));
 const selectedAfter=clone(selectedBefore);if(!inactive)for(const r of Object.values(selectedAfter))Object.assign(r,{state:'active',effectiveMaterial:material,overrides:[material]});
 const protectedAssetHashes=Object.fromEntries(Array.from({length:1878},(_,i)=>[`unreal/BreziTwin/Content/Brezi/Geometry/brezi-twin/StaticMeshes/DOM_${String(i+1).padStart(5,'0')}.uasset`,h]));
 protectedAssetHashes['unreal/BreziTwin/Content/Brezi/Geometry/brezi-twin/Materials/MAT_0102.uasset']=h;
 const r={status:inactive?'source-pool-coping-retained':'pool-coping-saved-reload-validated',nativeApplied:!inactive,restoring:false,actorMetadataWritten:false,rollbackErrors:[],selectedIds:ids,sourceMaterialSlot:'MAT_0102',excludedSharedSlotIds:ref.excludedSharedSlotIds,sourceManifestSha256:ref.sceneSha256,sourceObjSha256:ref.objSha256,recipe,recipeCanonicalJson,recipeSha256,pipelineFiles:expected.pipeline,grassInstanceCount:33769,selectedBefore,selectedAfter,protectedAssetHashes,sourcePreservationSnapshotSha256:h,assetHashes:{},renderedVerified:false};
 const reload={mapSaved:true,worldUnloaded:true,mapReloaded:true};
 if(inactive)Object.assign(r,{sourceOverridesRetained:28,candidateOverridesActive:0,sourceObjectsDeleted:0,sourceStateUnchangedAfterReload:true,sourceReload:reload,sourceMaterialNativeParameterReadback:false});
 else{
  Object.assign(r,{activationStarted:true,stagedReload:{...reload,allFourOwnedAssetsAbsentBeforeReload:true},activeReload:{...reload,allFourOwnedAssetsAbsentBeforeReload:true},verification:Object.fromEntries(['exact28Bindings','sourceVerticesUv0Unchanged','allOtherActorsAndGrassUnchanged','sourceBaseMaterialRetained','twoMapReloads','twoOwnedAssetUnloadAbsenceReadbacks','exactSavedGraphsEqual'].map(k=>[k,true]))});
  const m=ref.material,q=m.roughness,roles={albedo:'Diffuse',normalMap:'nor_gl',roughMap:'Rough'};
  const g={asset:material,recipeSha256,nodeCount:21,linkCount:19,textureSampleCount:3,parameters:m,mapping:'signed-dominant-axis-world-planar',normalGreenFlipCount:1,normalShaderGreenFlipCount:0,sourceUvSampled:false,worldPositionOffsetConnected:false,pixelDepthOffsetConnected:false,sourceScaleProvenance:ref.source.physicalScaleProvenance,nativeScalars:{period:m.tileMm/10,normalStrength:m.normalStrength,albedoMix:m.albedoMix,roughBase:q.base,roughAmplitude:q.amplitude,roughMean:q.mapMean,roughMin:q.min,roughMax:q.max,metallic:0,specular:.5},nativeVectors:{baseColor:m.baseColorLinear,tint:m.tintLinear},shaderSha256:clone(POOL_COPING_SHADER_HASHES),renderedVerified:false,residentMipsVerified:false,nativeNormalTangentNumericProof:false};
  for(const k of ['exactGraphVerified','allInputsAccountedFor','worldSpaceNormal','roughnessRemapped','roughnessAuthoredNotMeasured','albedoAuthoredColorConversion','implicitContinuousGradientsWithinEachPlanarFace','stockAutomaticViewMipBias'])g[k]=true;
  g.textures=Object.fromEntries(Object.entries(roles).map(([k,input])=>[k,{asset:`${owned}/Textures/T_${k}.T_${k}`,sourceSha256:ref.maps[input].sha256,pixels:[4096,4096],srgb:k==='albedo',greenFlipped:k==='normalMap',wrapXY:true,sourceDimensionReadback:true}]));
  r.activeMaterialProof=g;r.stagedMaterialProof=clone(g);
  r.assetHashes=Object.fromEntries(['Materials/M_PoolCoping.uasset',...Object.keys(roles).map(k=>`Textures/T_${k}.uasset`)].map(n=>[`unreal/BreziTwin/Content/Brezi/PoolCoping/R_${recipeSha256.slice(0,16)}/${n}`,h]));
 }
 return {sourceManifestSha256:ref.sceneSha256,pipelineFiles:expected.pipeline,lawnDetail:{instanceCount:33769},poolCoping:r,finalAssetHashes:{...protectedAssetHashes,...r.assetHashes}};
}
test('active and inactive contracts plus exact float32 scalar readback',()=>{
 for(const inactive of [false,true])assert.match(validatePoolCopingReceipt(fixture(inactive),expected).status,/package-inputs-validated$/);
 const f=fixture();for(const g of [f.poolCoping.activeMaterialProof,f.poolCoping.stagedMaterialProof])for(const k of Object.keys(g.nativeScalars))g.nativeScalars[k]=Math.fround(g.nativeScalars[k]);validatePoolCopingReceipt(f,expected);
});
const activeMutations={
 absent:f=>delete f.poolCoping,wrongIds:f=>f.poolCoping.selectedIds.pop(),excludedSteps:f=>f.poolCoping.excludedSharedSlotIds.pop(),source:f=>f.poolCoping.sourceManifestSha256=h,pipeline:f=>f.poolCoping.pipelineFiles={},recipe:f=>f.poolCoping.recipeCanonicalJson+=' ',foreignPrior:f=>f.poolCoping.selectedBefore[ids[0]].overrides=['/foreign'],wrongOverride:f=>f.poolCoping.selectedAfter[ids[0]].overrides=[],uvChange:f=>f.poolCoping.selectedAfter[ids[0]].sourceProof.maximumUv0Error=.1,topology:f=>f.poolCoping.selectedAfter[ids[0]].sourceProof.triangles=11,grass:f=>f.poolCoping.grassInstanceCount=33768,reload:f=>f.poolCoping.activeReload.mapReloaded=false,unload:f=>f.poolCoping.stagedReload.allFourOwnedAssetsAbsentBeforeReload=false,sourceAsset:f=>delete f.finalAssetHashes['unreal/BreziTwin/Content/Brezi/Geometry/brezi-twin/Materials/MAT_0102.uasset'],ownedAsset:f=>delete f.finalAssetHashes[Object.keys(f.poolCoping.assetHashes)[0]],changedGraph:f=>f.poolCoping.activeMaterialProof.nodeCount=20,period:f=>{for(const g of [f.poolCoping.activeMaterialProof,f.poolCoping.stagedMaterialProof])g.nativeScalars.period=500;},doubleFlip:f=>{for(const g of [f.poolCoping.activeMaterialProof,f.poolCoping.stagedMaterialProof])g.normalShaderGreenFlipCount=1;},mapSwap:f=>{for(const g of [f.poolCoping.activeMaterialProof,f.poolCoping.stagedMaterialProof])g.textures.normalMap.sourceSha256=ref.maps.Diffuse.sha256;},roughnessSrgb:f=>{for(const g of [f.poolCoping.activeMaterialProof,f.poolCoping.stagedMaterialProof])g.textures.roughMap.srgb=true;},shaderChanged:f=>{for(const g of [f.poolCoping.activeMaterialProof,f.poolCoping.stagedMaterialProof])g.shaderSha256.uv=h;},falseNativeProof:f=>{for(const g of [f.poolCoping.activeMaterialProof,f.poolCoping.stagedMaterialProof])g.nativeNormalTangentNumericProof=true;}
};
for(const [name,mutate] of Object.entries(activeMutations))test('reject active '+name,()=>{const f=fixture();mutate(f);assert.throws(()=>validatePoolCopingReceipt(f,expected));});
for(const [name,mutate] of Object.entries({activeLeft:f=>Object.assign(f.poolCoping.selectedAfter[ids[0]],{state:'active',overrides:['/candidate'],effectiveMaterial:'/candidate'}),nativeApplied:f=>f.poolCoping.nativeApplied=true,retainedAsset:f=>f.poolCoping.assetHashes={bad:h},missingReload:f=>delete f.poolCoping.sourceReload,noWorldProof:f=>f.poolCoping.sourceStateUnchangedAfterReload=false,falseGraphProof:f=>f.poolCoping.sourceMaterialNativeParameterReadback=true}))test('reject inactive '+name,()=>{const f=fixture(true);mutate(f);assert.throws(()=>validatePoolCopingReceipt(f,expected));});
